### ISSUE TITLE
Deep recursion on subroutine "DB::_get_reference_descriptor"

### ISSUE THREAD

**Issue by floreal** [Camelcade/Devel-Camelcadedb#38]
When debugging, sometime the debugger gets stuck in a deep recursion, and I get this message: `Deep recursion on subroutine "DB::_get_reference_descriptor" at /home/floreal/.plenv/versions/5.18.2/lib/perl5/site_perl/5.18.2/Devel/Camelcadedb.pm line 650.`

CPU load increase dramatically until I kill the running process. 

It didn't happen in previous versions of Devel::Camelcadedeb and Idea.

System information:
  * IDE name and version: IntelliJ IDEA 2018.3.3 (Community Edition) Build #IC-183.5153.38, built on January 9, 2019
  * Perl5 plugin version: v2018.3.5
  * `Devel::Camelcadedb` module version: v2018.3.0
  * JRE version: OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-2~14.04-b11)
  * Perl version: v5.18.2
  * Your OS name and version: Linux Mint (Linux 4.4.0-121-generic)

**Comment by hurricup** [comment]
Fixed in 37df788ffcc8130a22846fe68296da3a469c64e6
