### ISSUE TITLE
"Compilation failed in require" error attempting to debug perl script

### ISSUE THREAD

**Issue by BradWinslow** [Camelcade/Devel-Camelcadedb#43]
Getting the following messages when trying to debug a perl script with IntelliJ:

Listening on localhost:55083...
/usr/bin/perl -d:Camelcadedb /Users/bwinslow/git/bitbucket/agent-zero-service/appserverScripts/test_array.pl
(1)Connecting to the IDE from process 46666 at localhost:55083...
Connected
Disconnected
Connection closed at /Library/Perl/5.18/Devel/Camelcadedb.pm line 1296.
Compilation failed in require.
BEGIN failed--compilation aborted.

Process finished with exit code 255

IDE name and version:  Intellij IDEA 2018.1
Perl plugin:   2018.1.2
Devel::Camelcadedb:   v2019.1
Java: Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
Perl:  This is perl 5, version 18, subversion 2 (v5.18.2) built for darwin-thread-multi-2level
OS:   macOS High Sierra  version 10.13.6

**Comment by hurricup** [comment]
As you may see something happens on the script's side. Hard to say without accessing to your sources.
Does simple running works?

**Comment by BradWinslow** [comment]
Yes, simply running the script works


On Wed, Jul 3, 2019 at 10:13 AM Alexandr Evstigneev <
notifications@github.com> wrote:

> As you may see something happens on the script's side. Hard to say without
> accessing to your sources.
> Does simple running works?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Camelcade_Devel-2DCamelcadedb_issues_43-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DALJFWC7LOHT57S3Z7ELTLTDP5TMZ5A5CNFSM4H5H4C3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZFDN4I-23issuecomment-2D508180209&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=ii7sCkaI8p7vjIvqTQA-v_6aaq8eRRfYy6ZSnBoNVVk&m=x4Ahp1rmVC1mLmCZOw0LgxQb7VtneWRxxmz08pWxXgo&s=4U3HgP8hCpIszLRUgWNvo7taekh8LgbWzD_ZRlTcna0&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ALJFWC6QRHHE3BVDNURO34TP5TMZ5ANCNFSM4H5H4C3A&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=ii7sCkaI8p7vjIvqTQA-v_6aaq8eRRfYy6ZSnBoNVVk&m=x4Ahp1rmVC1mLmCZOw0LgxQb7VtneWRxxmz08pWxXgo&s=yeV7cAu1P2T1p6FDwdUTcMsmlRrNAnzKH9DSyGcp-Zg&e=>
> .
>


-- 
*Brad Winslow* | Agent Engineer
Mobile 310.658.3963

<http://appdynamics.com/>

Watch  <http://appdynamics.wistia.com/medias/56gnkuk6mv>our Video | Try
<https://portal.appdynamics.com/account/signup/signupForm>our FREE Trial |
Twitter  <http://www.twitter.com/appdynamics>| Facebook
<http://www.facebook.com/pages/AppDynamics/193264136815?ref=nf>|
appdynamics.com <http://www.appdynamics.com/>

**Comment by hurricup** [comment]
Ok. Debugger itself has just few runtime requres:
```
require Cwd;
require B::Deparse;
require JSON::XS;
```
Make sure they all available. I'd also tried to run `perl -MDevel::Camelcadedb -e 'print 42'` or smth. And see if it fails and if it provides more debugging information. Probably `Carp::Always` could help either

**Comment by BradWinslow** [comment]
perl -MDEVEL::Camelcadedb -e "print 42"

Can't start debugging session. In order to make it work, you should set up
environment variables:


PERL5_DEBUG_ROLE - set this to 'server' if you want to make Perl process
act as a server, and to 'client' to make it connect to IDEA.

PERL5_DEBUG_HOST - host to bind or connect, depending on role.

PERL5_DEBUG_PORT - host to listen or connect, depending on role.


Atm we've got:

 PERL5_DEBUG_ROLE=undefined

 PERL5_DEBUG_HOST=undefined

 PERL5_DEBUG_PORT=undefined



I am very new with Perl; my apologies.  What does "Carp::Always" refer to?




On Wed, Jul 3, 2019 at 11:02 AM Alexandr Evstigneev <
notifications@github.com> wrote:

> Ok. Debugger itself has just few runtime requres:
>
> require Cwd;
> require B::Deparse;
> require JSON::XS;
>
> Make sure they all available. I'd also tried to run perl
> -MDevel::Camelcadedb -e 'print 42' or smth. And see if it fails and if it
> provides more debugging information. Probably Carp::Always could help
> either
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Camelcade_Devel-2DCamelcadedb_issues_43-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DALJFWC3WXJ2ZWF3H52W7JR3P5TSUNA5CNFSM4H5H4C3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZFHVOI-23issuecomment-2D508197561&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=ii7sCkaI8p7vjIvqTQA-v_6aaq8eRRfYy6ZSnBoNVVk&m=CxbuBxR2CSV_khyfSFDXRe8WmAuyRBC67JVAhypl-qY&s=FURaNQP-or0ZpHwUDH2xjcr-7N75HRfzwQLvuigdks4&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ALJFWC7HZQLWMMNGU52SYXDP5TSUNANCNFSM4H5H4C3A&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=ii7sCkaI8p7vjIvqTQA-v_6aaq8eRRfYy6ZSnBoNVVk&m=CxbuBxR2CSV_khyfSFDXRe8WmAuyRBC67JVAhypl-qY&s=2_BtnEVNMDfnMlatwVECUBELlUr4o_hh7jyIHDT6bk8&e=>
> .
>


-- 
*Brad Winslow* | Agent Engineer
Mobile 310.658.3963

<http://appdynamics.com/>

Watch  <http://appdynamics.wistia.com/medias/56gnkuk6mv>our Video | Try
<https://portal.appdynamics.com/account/signup/signupForm>our FREE Trial |
Twitter  <http://www.twitter.com/appdynamics>| Facebook
<http://www.facebook.com/pages/AppDynamics/193264136815?ref=nf>|
appdynamics.com <http://www.appdynamics.com/>

**Comment by hurricup** [comment]
https://metacpan.org/pod/Carp::Always

**Comment by hurricup** [comment]
You may try to install this package and edit your installed `Camelcadedb` to add `use Carp::Always`  in the beginning.  This probably will give additional diagnostic when starting from the IDE

**Comment by BradWinslow** [comment]
I'm getting the following messages from the IDE (after adding use
Carp::Always)

Listening on localhost:59575...
/usr/bin/perl -d:Camelcadedb
/Users/bwinslow/git/bitbucket/agent-zero-service/appserverScripts/hello.pl
Connected
Disconnected
(1)Connecting to the IDE from process 9687 at localhost:59575...
Connection closed at /Library/Perl/5.18/Devel/Camelcadedb.pm line 1297.
DB::_set_up_after_connect(0) called at
/Library/Perl/5.18/Devel/Camelcadedb.pm line 1860
DB::_connect(10, 0) called at /Library/Perl/5.18/Devel/Camelcadedb.pm line
1954
require Devel/Camelcadedb.pm called at
/Users/bwinslow/git/bitbucket/agent-zero-service/appserverScripts/hello.pl
line 0
main::BEGIN() called at /Library/Perl/5.18/Devel/Camelcadedb.pm line 0
eval {...} called at /Library/Perl/5.18/Devel/Camelcadedb.pm line 0
Compilation failed in require.
 at /Users/bwinslow/git/bitbucket/agent-zero-service/appserverScripts/
hello.pl line 0.
main::BEGIN() called at
/Users/bwinslow/git/bitbucket/agent-zero-service/appserverScripts/hello.pl
line 0
eval {...} called at
/Users/bwinslow/git/bitbucket/agent-zero-service/appserverScripts/hello.pl
line 0
BEGIN failed--compilation aborted.
 at /Users/bwinslow/git/bitbucket/agent-zero-service/appserverScripts/
hello.pl line 0.

Process finished with exit code 255

On Wed, Jul 3, 2019 at 11:49 AM Alexandr Evstigneev <
notifications@github.com> wrote:

> You may try to install this package and edit your installed Camelcadedb
> to add use Carp::Always in the beginning. This probably will give
> additional diagnostic when starting from the IDE
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Camelcade_Devel-2DCamelcadedb_issues_43-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DALJFWCYYXL6D4VRWDMMODHLP5TYFHA5CNFSM4H5H4C3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZFLW2Y-23issuecomment-2D508214123&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=ii7sCkaI8p7vjIvqTQA-v_6aaq8eRRfYy6ZSnBoNVVk&m=grrR95-6fvL9x935M7ku2iEOCymlAG-qosQnT8dNfPk&s=4tlKYOqKwBi0M1rgSwIKuI573u_0bZMIEWYQbCfkhOk&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ALJFWC7EGTAM252MVKF3EYLP5TYFHANCNFSM4H5H4C3A&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=ii7sCkaI8p7vjIvqTQA-v_6aaq8eRRfYy6ZSnBoNVVk&m=grrR95-6fvL9x935M7ku2iEOCymlAG-qosQnT8dNfPk&s=dQt8i4mrjVNYoSXfX33MGBP34-ICBChUlodGtb3xhiA&e=>
> .
>


-- 
*Brad Winslow* | Agent Engineer
Mobile 310.658.3963

<http://appdynamics.com/>

Watch  <http://appdynamics.wistia.com/medias/56gnkuk6mv>our Video | Try
<https://portal.appdynamics.com/account/signup/signupForm>our FREE Trial |
Twitter  <http://www.twitter.com/appdynamics>| Facebook
<http://www.facebook.com/pages/AppDynamics/193264136815?ref=nf>|
appdynamics.com <http://www.appdynamics.com/>

**Comment by hurricup** [comment]
Dam. I've missed that. Don't you get a notification in the IDE that you are trying to use incompatible debugger module?
Please, update your IDE and plugin to the recent version, or install compatible debugger module. 
I believe this one https://metacpan.org/release/HURRICUP/Devel-Camelcadedb-2017.100.3
but not sure. 
I don't really remember how exactly it worked one and half year ago and will be glad to help with actual version problems

**Comment by BradWinslow** [comment]
Installing Devel-Camelcadedb-2017.1.1 seems to have fixed the issue.
Thanks for all your help!!

On Wed, Jul 3, 2019 at 12:01 PM Alexandr Evstigneev <
notifications@github.com> wrote:

> Dam. I've missed that. Don't you get a notification in the IDE that you
> are trying to use incompatible debugger module?
> Please, update your IDE and plugin to the recent version, or install
> compatible debugger module.
> I believe this one
> https://metacpan.org/release/HURRICUP/Devel-Camelcadedb-2017.100.3
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__metacpan.org_release_HURRICUP_Devel-2DCamelcadedb-2D2017.100.3&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=ii7sCkaI8p7vjIvqTQA-v_6aaq8eRRfYy6ZSnBoNVVk&m=vYmp1LI22Ta-JGWRypwDhHGtJGJfaOq5OMk4Cflk9q0&s=8gBsn0N4SAedrf5H76G6H_mZqa-o3SEG_eGzcFOlDjc&e=>
> but not sure.
> I don't really remember how exactly it worked one and half year ago and
> will be glad to help with actual version problems
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Camelcade_Devel-2DCamelcadedb_issues_43-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DALJFWCYJRRROEVQW7BRDKEDP5TZSHA5CNFSM4H5H4C3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZFMWSA-23issuecomment-2D508218184&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=ii7sCkaI8p7vjIvqTQA-v_6aaq8eRRfYy6ZSnBoNVVk&m=vYmp1LI22Ta-JGWRypwDhHGtJGJfaOq5OMk4Cflk9q0&s=WpOU1Mpz86FgDELrrFOvFtRptzZ8Pcx3b2VSFgCi3IM&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ALJFWC4FXDERPABYPQGMJJTP5TZSHANCNFSM4H5H4C3A&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=ii7sCkaI8p7vjIvqTQA-v_6aaq8eRRfYy6ZSnBoNVVk&m=vYmp1LI22Ta-JGWRypwDhHGtJGJfaOq5OMk4Cflk9q0&s=IBAA4qRzLmbFu25uFoEm9LshYNf-CXo_fm3ZY6EVJrY&e=>
> .
>


-- 
*Brad Winslow* | Agent Engineer
Mobile 310.658.3963

<http://appdynamics.com/>

Watch  <http://appdynamics.wistia.com/medias/56gnkuk6mv>our Video | Try
<https://portal.appdynamics.com/account/signup/signupForm>our FREE Trial |
Twitter  <http://www.twitter.com/appdynamics>| Facebook
<http://www.facebook.com/pages/AppDynamics/193264136815?ref=nf>|
appdynamics.com <http://www.appdynamics.com/>
